// This file is automatically generated. Do not modify it manually.
package main
var manifest = struct {
	ID      string
	Version string
}{
	ID:      "mattermost-plugin-open-ai",
	Version: "0.0.1",
}
